export default async function handler(req, res) {
  // CORS Headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { ingredients, language } = req.body;
    const apiKey = process.env.GEMINI_API_KEY;

    if (!apiKey) {
      return res.status(500).json({ error: "API Key missing in Vercel Environment Variables" });
    }

    const ingList = Array.isArray(ingredients) ? ingredients.join(', ') : ingredients;
    const lang = language === 'hi' ? 'Hindi' : 'English';

    const prompt = `You are an expert chef. Create a detailed, step-by-step recipe using these ingredients: ${ingList}. Language: ${lang}. Return response with clear sections: Title, Ingredients Needed, Step-by-Step Instructions, and Pro Tips.`;

    const googleUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

    const response = await fetch(googleUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [{
          parts: [{ text: prompt }]
        }]
      })
    });

    if (!response.ok) {
      const errorData = await response.text();
      console.error("Gemini API Error Response:", errorData);
      return res.status(500).json({ error: "Gemini API failed to respond" });
    }

    const data = await response.json();
    
    if (data.candidates && data.candidates[0]?.content?.parts[0]?.text) {
      const recipeText = data.candidates[0].content.parts[0].text;
      return res.status(200).json({ recipe: recipeText });
    } else {
      return res.status(500).json({ error: "No recipe generated by Gemini" });
    }

  } catch (error) {
    console.error("Backend Error:", error);
    return res.status(500).json({ error: error.message || "Failed to process recipe" });
  }
}
